/**
 * RAG Core Types - Unified Type Definitions
 * All RAG-related types and interfaces consolidated in one place
 */

// ========================================
// Basic Data Types
// ========================================

/**
 * File metadata interface (used by FileWatcher and extractFileMetadata)
 */
export interface FileMetadata {
  id: string
  name: string
  path: string
  size: number
  fileType: string
  createdAt: string   // ISO string
  modifiedAt: string  // ISO string
  hash: string
}

/**
 * Document metadata stored in VectorDB (unified metadata type)
 */
export interface DocumentMetadata {
  // File basic info
  fileName: string
  filePath: string
  fileType: string
  fileSize: number
  fileHash: string

  // Timestamps
  createdAt: string // ISO string
  modifiedAt: string // ISO string
  processedAt: string // ISO string

  // Optional extended fields
  tags?: string[]
  category?: string
  language?: string

  // User-defined fields (extensible)
  [key: string]: any
}

/**
 * Document chunk interface (simplified)
 */
export interface DocumentChunk {
  id: string
  fileId: string
  chunkIndex: number
  content: string
  embeddingId?: string
  metadata?: DocumentMetadata
}

/**
 * Custom metadata (simplified)
 */
export interface CustomMetadata {
  fileId: string
  key: string
  value: string
}

// ========================================
// Vector Store Types
// ========================================

/**
 * Vector document - common document format used by all providers
 */
export interface VectorDocument {
  // Unique identifiers
  id: string              // chunk-level unique ID
  doc_id: string          // document (file) level ID
  chunk_id: number        // chunk index
  
  // Content
  content: string         // actual text content
  vector?: number[]       // embedding vector (optional, generated by provider)
  
  // Metadata
  metadata: DocumentMetadata
  modelName?: string      // embedding model name (optional)
}

/**
 * Vector search result - common search result format returned by all providers
 */
export interface VectorSearchResult {
  // Document info
  id: string              // chunk-level unique ID
  content: string         // text content
  
  // Search scores
  score: number           // similarity score (0-1, higher is more similar)
  
  // Metadata
  metadata: DocumentMetadata
  chunkIndex: number      // chunk index (compatibility)
}

/**
 * Vector search options - provider-independent common search options (simplified)
 */
export interface VectorSearchOptions {
  topK?: number                                           // maximum number of results
  scoreThreshold?: number                                 // minimum score threshold
}

/**
 * Index statistics
 */
export interface IndexStats {
  totalVectors: number      // total vector count
  dimensions: number        // vector dimensions
  indexSize?: number        // index size (bytes)
  lastUpdated?: Date        // last update time
}

// ========================================
// LanceDB Types (formerly in separate files)
// ========================================

/**
 * RAG-optimized simple document schema for LanceDB
 * GPT recommended approach: vector, text, doc_id, chunk_id, metadata (JSON string)
 */
export interface RAGDocumentRecord extends Record<string, unknown> {
  vector: number[] // embedding vector
  text: string // original text to pass to LLM (chunk content)
  doc_id: string // document identifier (file path based)
  chunk_id: number // chunk index
  metadata: string // metadata stored as JSON string
  model_name: string // embedding model name
}

/**
 * LanceDB search result (simplified)
 */
export interface RAGSearchResult {
  vector: number[]
  text: string
  doc_id: string
  chunk_id: number
  metadata: DocumentMetadata
  _distance?: number // distance value provided by LanceDB
  score?: number // calculated similarity score
}

/**
 * LanceDB table creation options (simplified)
 */
export interface LanceDBTableOptions {
  tableName: string
  mode?: 'create' | 'overwrite' | 'append'
  embeddingFunction?: any // LanceDBEmbeddingFunction
}

/**
 * Search filter options (simplified)
 */
export interface SearchFilters {
  fileTypes?: string[]
  docIds?: string[]
  tags?: string[]
  dateRange?: {
    start: string
    end: string
  }
}

// ========================================
// Search Types (consolidated from multiple files)
// ========================================

export interface SearchOptions {
  topK?: number
  fileTypes?: string[]
  metadataFilters?: Record<string, string>
  searchType?: 'semantic' | 'hybrid' | 'keyword'
  useSemanticSearch?: boolean
  useHybridSearch?: boolean
  semanticWeight?: number
  scoreThreshold?: number
}

export interface SearchResult {
  content: string
  score: number
  semanticScore?: number
  keywordScore?: number
  hybridScore?: number
  metadata: Record<string, any>
  chunkIndex: number
}

// ========================================
// Model Information Types
// ========================================

export interface ModelInfo {
  name: string
  service: string
  dimensions: number
  model?: string
}

export interface IndexInfo {
  documentCount: number
  indexPath?: string
}

/**
 * Embedding model metadata
 */
export interface EmbeddingMetadataModel {
  id: string
  modelName: string
  serviceName: string
  dimensions: number
  modelVersion?: string
  configHash: string
  isActive: boolean
  totalDocuments: number
  totalVectors: number
  createdAt: Date
  lastUsedAt: Date
}

// ========================================
// Event Types
// ========================================

/**
 * File change event
 */
export class FileChangeEvent {
  constructor(
    public readonly type: 'added' | 'changed' | 'removed',
    public readonly path: string
  ) {}
}

/**
 * Processing status
 */
export class ProcessingStatus {
  constructor(
    public readonly isProcessing: boolean,
    public readonly queueSize: number,
    public readonly lastProcessedFile?: string
  ) {}
}

// ========================================
// Constants
// ========================================

/**
 * Default table options for LanceDB
 */
export const DEFAULT_TABLE_OPTIONS: LanceDBTableOptions = {
  tableName: 'documents',
  mode: 'create'
}

// ========================================
// Utility Functions
// ========================================

/**
 * Convert DocumentMetadata to legacy FileMetadata format
 */
export function documentMetadataToLegacyFileMetadata(metadata: DocumentMetadata): any {
  return {
    id: metadata.filePath, // use path as id (existing approach)
    path: metadata.filePath,
    name: metadata.fileName,
    size: metadata.fileSize,
    modifiedAt: new Date(metadata.modifiedAt),
    createdAt: new Date(metadata.createdAt),
    fileType: metadata.fileType,
    hash: metadata.fileHash,
    indexedAt: new Date(metadata.processedAt)
  }
}